### ISSUE TITLE
Desperately trying to create field that must reuse an existing Global Choice

### ISSUE THREAD

**Issue by JMG74** [MscrmTools/Javista.AttributesFactory#19]
I'm using your template and I'm trying desperately to create a new field that must reuse an existing **Global Choice**.
As the columns headers comments are not crystal clear to me, I've tried all the possible combinations but none is working !... perhaps a bug is hiding behind ?

If I want to create a new field called "new_field" that must reuse the existing Global Choice called "new_gender_code", I will set column C to "new_field" and column D to "Choice"... and could you please explain what must be set in the columns P and Q ?

Many thanks in advance for your help, and all the best.

**Comment by MscrmTools** [comment]
First, please ensure you are using the latest version of the tool.
Then, column P should be left empty and column Q should contain the name of the global choice.
If it does not work, please tell me

**Comment by JMG74** [comment]
Hi,

Yes, I confirm that I'm using the last version of the tool (1.2022.6.13)
and the last version of the template.
I've already tested all the combinations and I confirm that with P empty
and Q set to the name of the global choice, I'm getting the following
update error : "Object reference not set to an instance of an object"

Thanks in advance for your help.

**Comment by MscrmTools** [comment]
The issue should be fixed in latest version released today

**Comment by JMG74** [comment]
I've just loaded the new release 1.2022.5.56 and reapplied my test case but I'm still getting an error with a different message than before : 
`Could not find an option set with specified name : new_field` 

Don't you get the same error on your side when testing the test case summarized below?
1. First, create directly in Dataverse a global option set called "new_gender_code" with 2 values ("F" and "M")
2. Create a new field called "new_field" that must reuse the existing Global Choice called "new_gender_code". According to your instructions, column P is empty and column Q contains "new_gender_code".
4. Processing the attribute generates the error "Could not find an option set with specified name : new_field".

Thks

**Comment by MscrmTools** [comment]
It does work on my side 
![image](https://user-images.githubusercontent.com/10774317/173539871-fcb78d14-2be4-4551-bb6b-36cdb807eb67.png)

Are you sure you have the latest version of Attributes Factory (1.2022.6.14)?

**Comment by JMG74** [comment]
Hi/Bonjour Tanguy

Thkx for your feedback.

Yes, I confirm that I'm using the last version of Attributes Factory (1.2022.6.14)... in fact, in one of my previous post I erroneously gave you the version of the XrmToolBox utility rather than the version of the Attribute Factory tool!! sorry for that!
I even uninstalled/reinstalled it to be sure that I'm using the last version.

According to your screenshots, I can see that we are not testing the same thing.
Here is what I'm trying to achieve: 
1) Create a field with schema name "uge_jmg_tst_gender_code" and at the same time create a global choice called "uge_jmg_tst_gender_code" ==> this step works perfectly
2) Create a new field "uge_jmg_tst_gender_**again**_code" as a Choice based on my global choice created at step 1 ==> error "Could not find an option set with specified name: uge_jmg_tst_gender_again_code". 

According to the error message, it seems that the Attribute Factory is trying to create a new Choice... but this not what I need... I would like to create a new field reusing the existing global choice.

Please find attached my screen shots and my Excel file used for this test. 
![image](https://user-images.githubusercontent.com/13162921/173999671-dc00dbf7-5a92-4d91-a63c-6e3e6c020015.png)
[Attributes_Template_NEW_DEBUG.xlsx](https://github.com/MscrmTools/Javista.AttributesFactory/files/8916018/Attributes_Template_NEW_DEBUG.xlsx)

PS: Étant moi-même francophone, si vous le souhaitez, nous pourrions temporairement échanger en français pour être sûr de bien nous comprendre.

**Comment by MscrmTools** [comment]
Ok, I think I found the bug and fixed it.

Can you try with this version?
[Javista.AttributesFactory.zip](https://github.com/MscrmTools/Javista.AttributesFactory/files/8920363/Javista.AttributesFactory.zip)

**Comment by JMG74** [comment]
Great !! this new release (1.2022.6.15) is **working perfectly** ! Thank you very much!!

Finally, here is a remark about the comment of cell P2 in the template. I've highlighted in yellow the text that could be removed or adapted according to the recent changes made for managing the Choice/OptionSet.
![image](https://user-images.githubusercontent.com/13162921/174224390-e75d13b4-f8b2-44d1-9b17-9217be3e0487.png)

Many thanks again!
